language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  matrix:
  - secure: DbD55eMkwbRhybaWCdjkD19V1bl3LU1azbVy/UsWSpDGRRgXWOuvb+gt1Tib+N4vJYYOaLdk0dRPQaa1RJWFobqK/G4DjcbZpnWEX6ig6wODy7RNjpQNbSmAsX8KAd/vxEu4iPTa/0cqVkf5GPpPsHeZbJB7sAM8rc/VxNuBk+Qk3LUQOEqMBI+jluwYf8ck5DSQfxB9AaNA3NsqtU1e+8P/y9qggolmYFTKtc+UsiPyAJNDboao/5KVwIKsgxWfLKPAuwn+mJL59JN5V3n6xR/jGq5qXb2FSyQoVdUiY7rVcDLgIz372dxoQWwFCjFOu0AcOpV2ikmmdeGcgXGJF0ZP0GVYa6ORBSqR76HB95INJ5uBVaBMakVhrLXxNmoGPpeQhnswuQaaNiJ0CeNQ3SFc8zZ5BrAtMw+LM7uvpkLI4l5cfhwaoHdgwMNfjbLOpTZZDl5ySpkftyb5OhI32htXFzhKQk3uUnud8c0ZF8eUJw7kdtbA0w9V+l8X/r3OXLbrNbNEwLsN7091jERDT7zxKnLmq71Rnyx8bbpwb9+hvbKKrCNnBUk5crvcO5KshkGwfh/y4aOKGJYR3+/PIj7uqtrJWniQK0TUl5rB0b48oTjerR53jwvnke5RxRPPMDXZyGv2TdPXuRJFMPHDg18fYs8veJp0qdb5YvKIRmg=
